os: linux
dist: bionic
language: python

python:
  - '3.6'
before_install:
  - sudo apt-get install -y mash
before_script:
  - pip3 install pytest
  - pip3 install coveralls
script:
  - coverage run -m pytest
after_success:
  - coveralls
